### ISSUE TITLE
有一定几率出现: kalu: checkDict ==> code = -80008

### ISSUE THREAD

**Issue by HeXsheng** [153437803/CardOCR#1]
出现 kalu: checkDict ==> code = -80008,导致识别失败,请问这是什么情况？

**Comment by 153437803** [comment]
![tim 20181206124714](https://user-images.githubusercontent.com/10386505/49562125-2ac6ad00-f955-11e8-9bbb-b2611cb400c1.png)

**Comment by 153437803** [comment]
你看着， 你的这个文件有没有， 我换到cache文件下面了, 有些机型可能默认不会创建files文件夹

**Comment by 153437803** [comment]
你啥手机啊

**Comment by HeXsheng** [comment]
红米Note 5

**Comment by HeXsheng** [comment]
一般第一次初始化就会报错，然后我重复初始化一次就好了

**Comment by 153437803** [comment]
你看看， 你第一次出错的时候， 那个字典文件在不在，如果还在， 你就发生错误， 再执行一次

**Comment by HeXsheng** [comment]
我测了,文件一直在的，没有碰到一次是因为文件不在导致的初始化错误呢。
然后我用个循环重复初始化,现在发现最多重复三次,就能够初始化成功。

**Comment by HeXsheng** [comment]
我换了个测试机之后,出现这个问题的几率大幅度下降,可能跟手机有关吧?

**Comment by WyangMiss** [comment]
@153437803 我进入扫描界面  不扫描身份证  点击手机虚拟键返回  低配的手机会闪退

**Comment by 153437803** [comment]
@WyangMiss 相机的分辨率， 识别准确就需要成像清楚

**Comment by 153437803** [comment]
@WyangMiss 具体要看你手机啥原因崩了的
