### ISSUE TITLE
华为手机黑屏

### ISSUE THREAD

**Issue by WyangMiss** [153437803/CardOCR#3]
在部分手机上扫描页面出现黑屏   机型:华为PAR AL100 版本8.1.0

**Comment by MrAugust** [comment]
@WyangMiss  没有相机权限的缘故吧！在其他不黑屏的手机上，你能正常识别吗？我测试一直返回
/** 图像错误 */
#define STATUS_BADIMAGE				(-80011)

**Comment by WyangMiss** [comment]
@MrAugust 权限是已经打开的  测试出很多手机不适配

**Comment by 153437803** [comment]
1.手机黑屏， 就是camera打开失败了， surfaceview初始化失败了， 你要在你有问题的那个机型上先把camera问题解决了
2.图像错误，在你手机横屏放的时候，你把你camera的预览分辨率调到最小， 可能是因为byte[]太大了

**Comment by 153437803** [comment]
应该解决了， 图像错误， 是因为有些手机屏幕不是16.9的， 解析宽高出错了， 改成相机预览尺寸了

**Comment by 153437803** [comment]
@WyangMiss @MrAugust 你们试试看还有没有图像错误

**Comment by MrAugust** [comment]
仍有图像错误返回，如下为摘选的日志：
E/kalu: checkDict ==> code = 0
E/kalu: result ==> width = 1280, height = 960
I/exocrenginec.so: Java_exocr_exocrengine_EXOCREngine_nativeRecoIDCardRawdat
I/exocrenginec.so: Width=1280, Height=960, pixelbyte=1, pitch=1280, maxSize=4096
I/exocrenginec.so: ret = -80011
parameters.getSupportedPreviewSizes()中返回的预览分辨率包含1280*960和1280*720，手动调整预览分辨率为1280*720（当前屏幕分辨率）或maxSize=10240，都返回-80011
相同的程序，小米8（Android版本9.0）上已经可以正常识别身份证
请问下，libexocrenginec.so是开源的吗？

**Comment by 153437803** [comment]
![tim 20181221171147](https://user-images.githubusercontent.com/10386505/50334546-9dce4700-0543-11e9-8cee-98d947068f77.png)
这个maxSize 你在调大些试一下
libexocrenginec.so不是开源的， 我也只有.a静态库，和调用c文件，字典我在readme有提过

**Comment by 153437803** [comment]
也有一种可能， 这个也许只支持 640*480比例的, 别的不行

**Comment by 153437803** [comment]
@MrAugust  你看看你那个小米， 分辨率是多少

**Comment by 153437803** [comment]
![tim 20181221172016](https://user-images.githubusercontent.com/10386505/50334948-c86ccf80-0544-11e9-907e-33c59a3d34a0.png)
@MrAugust 这是我这边的

**Comment by 153437803** [comment]
相机预览画面变形了吗

**Comment by MrAugust** [comment]
@153437803 应该是跟buffer size没有关系，米8像素更高，采样的图片应该更大。我再试试其他预览分辨率

**Comment by MrAugust** [comment]
有变形

**Comment by 153437803** [comment]
我再看看吧， 应该是相机这个有问题

**Comment by 153437803** [comment]
byte[] 这一帧 图片宽高有点问题

**Comment by 153437803** [comment]
@MrAugust 我改了了， 你试试看看出问题（画面预览变形的那个机子），还有问题吗

**Comment by ASDbobo** [comment]
第一次安装后能拍照,返回就提示初始化失败,然后打开扫描页面后就一直黑屏,进去提示初始化失败,代码里定位到   // step2: 检测字典是否正确
        boolean okDict = checkDict(path);
        Log.e("检测字典是否正确",okDict+"");
        if (!okDict) {

            clearDict();

            return false;
        }
显示字典不正确.
用了是你今天发的lib_ocr当库.

**Comment by MrAugust** [comment]
@153437803 可以识别了，但就是识别速度比较慢，需要10多秒

**Comment by 153437803** [comment]
@MrAugust 识别慢是因为， 相机成像分辨率设置的640 320， 所以比较慢

**Comment by 153437803** [comment]
@MrAugust 识别慢是因为， 相机成像分辨率设置的640 480， 所以比较慢

**Comment by 153437803** [comment]
@ASDbobo 初始化失败，这个暂时不知道为什么
1. 可能你没打开sd卡权限
2. 可能 系统内置缓存大小有限制， 不同机子限制不一样

失败了， 你就初始化几次

**Comment by MrAugust** [comment]
640*480是识别不出来，我改为1280 960

**Comment by ASDbobo** [comment]
@153437803 权限给了,就第一次安装时可以扫描,然后扫描身份证正面也有解析的值,之后再打开扫描界面就黑屏,提示初始化失败
