### ISSUE TITLE
无法从本地图片识别数据

### ISSUE THREAD

**Issue by hVenus** [153437803/CardOCR#5]
使用
public static EXOCRModel decodeBitmap(Bitmap bitmap)
以及
public static EXOCRModel decodeBitmap(final String path)
均不成功，始终返回-80011,应该是 “图像错误”这类问题。

那么请问读本地图片对图片有什么特别要求？

摄像头拍的照片不行，甚至使用public static EXOCRModel decodeByte(final byte[] image, final int width, final int height)这里面的数据保存了一份照片文件也不行。

是libexocrenginec.so不支持？

**Comment by hVenus** [comment]
还有，这个库能读驾驶证不？只能读身份证吗？

**Comment by 153437803** [comment]
只能读二代身份证， 解析本地图片对bitmap图片质量要求高，bitmap不清楚也识别不出来

**Comment by liganggit** [comment]
libexocrenginec.so 和 zocr0.lib 来源是哪里  是开源的吗？

**Comment by 153437803** [comment]
不是开源的

**Comment by liganggit** [comment]
好像来自华为…… 有相关的文档推荐吗？

**Comment by liganggit** [comment]
平安科技的任意门和华为APP都用过这个

**Comment by 153437803** [comment]
不好意思 没有

**Comment by piaobuliao** [comment]
@liganggit 应该是易道博识开发的
